default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  
  # Configuração para desenvolvimento local com PostgreSQL
  host: 34.46.119.81
  port: 5432
  database: fitclass 
  username: artur
  password: h2#j9f<&1E;`y;<?
  # ======================================================

development:
  <<: *default
  database: fitclass 

test:
  <<: *default
  database: fitclass_test 



production:
  <<: *default
  
 
  host: /cloudsql/<%= ENV['CLOUD_SQL_CONNECTION_NAME'] %>
  
  database: <%= ENV['DB_DATABASE'] %> 
  username: <%= ENV['DB_USERNAME'] %> 
  password: <%= ENV['DB_PASSWORD'] %>